[server]
headless = true
port = 8501
enableCORS = false

[theme]
base="light"
primaryColor="#FF6F61"        # Coral red
secondaryBackgroundColor="#FFF5E1"
backgroundColor="#FDE2FF"     # Light pink/lavender
textColor="#2C2C54"
font="sans serif"

